= Quantiply Data Science Challenge

== Overview

At Quantiply, we develop cutting edge models to solve complex problems. Our customers, financial institutions, are conservative. They are used to the rule based systems (https://www.casewareanalytics.com/blog/rules-based-vs-advanced-analytics-%E2%80%93-do-you-have-choose), which is easy to understand even though these systems yield high false positive rates. In addition, the end users may not have enough machine learning/AI background to comprehend the explanations that are accessible to ML practitioners. One of the major differentiators of Quantiply is our explainable AI (XAI) platform. We developed an XAI framework to help explain the decision making process of complex models like neural networks.

We would like to introduce the challenge to you too. We want you to live the life of a Data Scientist at Quantiply. On a daily basis, we tackle challenging problems, from building state-of-the-art unsupervised generative models, to explaining the how and the why of the decision-making process of the models.

Here are some XAI frameworks for your reference:

. https://arxiv.org/pdf/1602.04938v1.pdf
. http://papers.nips.cc/paper/7062-a-unified-approach-to-interpreting-model-predictions.pdf
. https://homes.cs.washington.edu/~marcotcr/aaai18.pdf
. https://github.com/datascienceinc/Skater

NOTE: Note, we are not satisfied with any of the methods above. We of course do not expect you to develop a new method over such a short time.

== Dataset

For this assignment, we have picked the *Chicago Crime Dataset*. You can download and learn more about the dataset at: https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2

The size of the dataset is approx. 1.6 GB.

*The target variable is `Primary Type`. It is a multi-class classification problem.*

== Our expectation

This challenge is very open ended. What we would you like to demonstrate are the following:

. Research what XAI is.
. Show how you approach this problem, let us know your thoughts.
. Build a classification model on the provided dataset.
. Provide explanations to your predictions.

=== Deliverables

- Submit a document that elaborates your thoughts on these methods, such as the basic concepts, advantages, drawbacks, etc.
- Use the classification model as an opportunity to demonstrate your data science skills.
- *Also, please let us know what you would like to do if you were given more time.*
- You can use any programming language of your choice.
- You can present your findings in any format as you deem clear.
- Instructions to run your scripts.

== Instructions on how to use Github

. *Its really important that you push your code regularly to Github. We leverage Github significantly to help us maintain our code base. Kindly ensure that you push your code regularly and NOT push your script only after its completed.* 
. *Issues:* If you have any questions, please raise an issue/concern/question by using the *Issues* tab on Github. Ensure to tag *Ryan Compton* on the issue so that he can work with you and resolve the issue/concern/question.
. *Projects:* We would like to see how you scope and plan projects. It is extremely important that the candidate is able to work independently and plan a their own https://www.scrum.org/resources/blog/typical-sprint-play-play[Sprint].

== Deadline

You will be given *two weeks* from the day the assignment was assigned to you. 

== Notes

Should you have any questions, feel free to reach out to Ryan via email or text or call.

We really want this assignment to be enjoyable and an opportunity for you to learn something new. Please reach out to us with any questions you may have.

*Ryan Contact Details* +
Ryan Compton +
Email id: compton@quantiply.com +
Mobile No.: 480.694.2307 +

= Thank​ ​you​ ​for​ ​your​ ​hard work! Good luck!



Song, T.-B., Chen, Y., Chung, C.-H., Yang, Y. M., Bob, B., Duan, H.-S., et al. (2014). Nanoscale Joule Heating and Electromigration Enhanced Ripening of Silver Nanowire Contacts. ACS Nano, 8(3), 2804–2811. http://doi.org/10.1021/nn4065567

